services:
  marketdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
    - 5432:5432
    volumes:
      - ./marketdb/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  marketsvc:
    build:
      context: ./marketsvc
      dockerfile: Dockerfile
    volumes:
      - ./marketsvc:/code/
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      FLASK_SERVER_PORT: 9090
    ports:
    - 9090:9090
    command:
      - python
      - server.py
    depends_on:
      marketdb:
        condition: service_healthy
