services:
  mydb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
    - 5432:5432
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  mysvc:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mysvc.py:/code/mysvc.py
